---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bmc-sno
  namespace: ztp-sno
data:
  password: <REPLACE_WITH_BASE64_BMC_ADMIN_PASSWORD>
  username: <REPLACE_WITH_BASE64_BMC_ADMIN_USERNAME>
