apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-configuration
spec:
  preProvisioningOSDownloadURLs: {}
  provisioningNetwork: Disabled
  provisioningOSDownloadURL: "<REPLACE_WITH_QCOW2_IMAGE_+_SHA256SUM>"
  virtualMediaViaExternalNetwork: true
  watchAllNamespaces: true
